//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNATURA_PERTENECE_PLAN_ESTU
    {
        public decimal IDENTIFICADORASIGNATURA { get; set; }
        public decimal IDENTIFICADORPLANESTUDIOS { get; set; }
        public Nullable<decimal> SEMESTRE { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
        public virtual PLANESTUDIO PLANESTUDIO { get; set; }
    }
}
