//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public decimal IDENTIFICADORCURSO { get; set; }
        public decimal IDENTIFICADORASIGNATURA { get; set; }
        public decimal IDENTIFICADORUSUARIO { get; set; }
        public string NOMBRECURSO { get; set; }
        public string ESTADOCURSO { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
        public virtual DOCENTE DOCENTE { get; set; }
    }
}
