//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public DEPARTAMENTO()
        {
            this.DOCENTEs = new HashSet<DOCENTE>();
            this.GRUPO_INVESTIGACION = new HashSet<GRUPO_INVESTIGACION>();
            this.PROGRAMAs = new HashSet<PROGRAMA>();
        }
    
        public decimal IDENTIFICADORDEPARTAMENTO { get; set; }
        public string NOMBREDEPARTAMENTO { get; set; }
        public string ESTADODEPARTAMENTO { get; set; }
        public string CODIGODEPARTAMENTO { get; set; }
    
        public virtual ICollection<DOCENTE> DOCENTEs { get; set; }
        public virtual ICollection<GRUPO_INVESTIGACION> GRUPO_INVESTIGACION { get; set; }
        public virtual ICollection<PROGRAMA> PROGRAMAs { get; set; }
    }
}
