//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMA
    {
        public PROGRAMA()
        {
            this.PLANESTUDIOS = new HashSet<PLANESTUDIO>();
            this.DEPARTAMENTOes = new HashSet<DEPARTAMENTO>();
        }
    
        public decimal IDENTIFICADORPROGRAMA { get; set; }
        public decimal IDENTIFICADORFACULTAD { get; set; }
        public string NOMBREPROGRAMA { get; set; }
        public string DESCRIPCIONPROGRAMA { get; set; }
        public string JORNADAPROGRAMA { get; set; }
        public Nullable<decimal> DURACIONPROGRAMA { get; set; }
        public string ADMISIONPROGRAMA { get; set; }
        public Nullable<decimal> CODIGOSNIESPROGRAMA { get; set; }
        public string PERIODODURACIONPROGRAMA { get; set; }
        public string ESTADOPROGRAMA { get; set; }
        public string MODALIDADPROGRAMA { get; set; }
    
        public virtual FACULTAD FACULTAD { get; set; }
        public virtual ICollection<PLANESTUDIO> PLANESTUDIOS { get; set; }
        public virtual ICollection<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
    }
}
