//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionInfraestructura.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.FRANJA_HORARIA = new HashSet<FRANJA_HORARIA>();
        }
    
        public decimal IDENTIFICADORCURSO { get; set; }
        public decimal IDENTIFICADORASIGNATURA { get; set; }
        public decimal IDENTIFICADORUSUARIO { get; set; }
        public string NOMBRECURSO { get; set; }
        public string ESTADOCURSO { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
        public virtual ICollection<FRANJA_HORARIA> FRANJA_HORARIA { get; set; }
    }
}
