//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionInfraestructura.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRANJA_HORARIA
    {
        public decimal IDENTIFICADORFRANJA { get; set; }
        public decimal IDENTIFICADORCURSO { get; set; }
        public decimal IDENTIFICADORRECURSO { get; set; }
        public string HORAINICIOFRANJA { get; set; }
        public string HORAFINFRANJA { get; set; }
        public string DIAFRANJA { get; set; }
        public string ESTADOFRANJA { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual RECURSO RECURSO { get; set; }
    }
}
