//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionInfraestructura.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECURSO
    {
        public RECURSO()
        {
            this.FRANJA_HORARIA = new HashSet<FRANJA_HORARIA>();
        }
    
        public decimal IDENTIFICADORRECURSO { get; set; }
        public decimal IDTIPORECURSO { get; set; }
        public decimal IDENTIFICADORFACULTAD { get; set; }
        public string NOMBRERECURSO { get; set; }
        public string ESTADORECURSO { get; set; }
    
        public virtual FACULTAD FACULTAD { get; set; }
        public virtual ICollection<FRANJA_HORARIA> FRANJA_HORARIA { get; set; }
        public virtual TIPORECURSO TIPORECURSO { get; set; }
    }
}
