//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionInfraestructura.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALON
    {
        public SALON()
        {
            this.FRANJA_HORARIA = new HashSet<FRANJA_HORARIA>();
            this.SALON_DICTA_CURSO = new HashSet<SALON_DICTA_CURSO>();
        }
    
        public decimal IDENTIFICADORSALON { get; set; }
        public decimal IDENTIFICADORFACULTAD { get; set; }
        public string NOMBRESALON { get; set; }
        public string ESTADOSALON { get; set; }
    
        public virtual FACULTAD FACULTAD { get; set; }
        public virtual ICollection<FRANJA_HORARIA> FRANJA_HORARIA { get; set; }
        public virtual ICollection<SALON_DICTA_CURSO> SALON_DICTA_CURSO { get; set; }
    }
}
