//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionContenidos.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        public CATEGORIA()
        {
            this.ATRIBUTOes = new HashSet<ATRIBUTO>();
            this.BLOQUEs = new HashSet<BLOQUE>();
            this.CONTENIDOes = new HashSet<CONTENIDO>();
        }
    
        public decimal IDENTIFICADORCATEGORIA { get; set; }
        public string NOMBRECATEGORIA { get; set; }
        public string DESCRIPCIONCATEGORIA { get; set; }
        public string ESTADOCATEGORIA { get; set; }
        public Nullable<decimal> VISIBLEPRINCIPALCATEGORIA { get; set; }
    
        public virtual ICollection<ATRIBUTO> ATRIBUTOes { get; set; }
        public virtual ICollection<BLOQUE> BLOQUEs { get; set; }
        public virtual ICollection<CONTENIDO> CONTENIDOes { get; set; }
    }
}
