//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionContenidos.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CONTENIDOes = new HashSet<CONTENIDO>();
        }
    
        public decimal IDENTIFICADORUSUARIO { get; set; }
        public string EMAILINSTITUCIONALUSUARIO { get; set; }
        public string PASSWORDUSUARIO { get; set; }
        public string IDENTIFICACIONUSUARIO { get; set; }
        public string NOMBRESUSUARIO { get; set; }
        public string APELLIDOSUSUARIO { get; set; }
        public string ESTADOUSUARIO { get; set; }
    
        public virtual ICollection<CONTENIDO> CONTENIDOes { get; set; }
    }
}
