//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionContenidos.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOQUE
    {
        public decimal IDENTIFICADORBLOQUE { get; set; }
        public decimal IDENTIFICADORCATEGORIA { get; set; }
        public Nullable<decimal> POSICIONXBLOQUE { get; set; }
        public Nullable<decimal> POSICIONYBLOQUE { get; set; }
        public Nullable<decimal> ANCHOBLOQUE { get; set; }
        public Nullable<decimal> ALTURABLOQUE { get; set; }
        public Nullable<decimal> OFFSETBLOQUE { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
