//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionContenidos.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETIQUETA
    {
        public ETIQUETA()
        {
            this.CONTENIDOes = new HashSet<CONTENIDO>();
        }
    
        public decimal IDENTIFICADORETIQUETA { get; set; }
        public string NOMBREETIQUETA { get; set; }
        public string DESCRIPCIONETIQUETA { get; set; }
    
        public virtual ICollection<CONTENIDO> CONTENIDOes { get; set; }
    }
}
