//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNATURA
    {
        public ASIGNATURA()
        {
            this.ASIGNATURA_PERTENECE_PLAN_ESTU = new HashSet<ASIGNATURA_PERTENECE_PLAN_ESTU>();
            this.CURSOes = new HashSet<CURSO>();
        }
    
        public decimal IDENTIFICADORASIGNATURA { get; set; }
        public string NOMBREASIGNATURA { get; set; }
        public string CORREQUISITOSASIGNATURA { get; set; }
        public string PREREQUISITOSASIGNATURA { get; set; }
        public Nullable<decimal> CREDITOSASIGNATURA { get; set; }
        public string MODALIDADASIGNATURA { get; set; }
        public string CLASIFICACIONASIGNATURA { get; set; }
        public string ESTADOASIGNATURA { get; set; }
        public string DESCRIPCIONASIGNATURA { get; set; }
        public string CODIGOASIGNATURA { get; set; }
    
        public virtual ICollection<ASIGNATURA_PERTENECE_PLAN_ESTU> ASIGNATURA_PERTENECE_PLAN_ESTU { get; set; }
        public virtual ICollection<CURSO> CURSOes { get; set; }
    }
}
