//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCENTE
    {
        public DOCENTE()
        {
            this.CURSOes = new HashSet<CURSO>();
            this.GRUPO_INVESTIGACION = new HashSet<GRUPO_INVESTIGACION>();
        }
    
        public decimal IDENTIFICADORUSUARIO { get; set; }
        public decimal IDENTIFICADORDEPARTAMENTO { get; set; }
        public string EMAILINSTITUCIONALUSUARIO { get; set; }
        public string PASSWORDUSUARIO { get; set; }
        public string IDENTIFICACIONUSUARIO { get; set; }
        public string NOMBRESUSUARIO { get; set; }
        public string APELLIDOSUSUARIO { get; set; }
        public string ESTADOUSUARIO { get; set; }
        public string CODIGODOCENTE { get; set; }
    
        public virtual ICollection<CURSO> CURSOes { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual ICollection<GRUPO_INVESTIGACION> GRUPO_INVESTIGACION { get; set; }
    }
}
