//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANESTUDIO
    {
        public PLANESTUDIO()
        {
            this.ASIGNATURAs = new HashSet<ASIGNATURA>();
        }
    
        public decimal IDENTIFICADORPLANESTUDIOS { get; set; }
        public decimal IDENTIFICADORPROGRAMA { get; set; }
        public string NOMBREPLANESTUDIOS { get; set; }
        public string DESCRIPCIONPLANESTUDIOS { get; set; }
        public string FECHAINICIOPLANESTUDIOS { get; set; }
        public string FECHAFINPLANESTUDIOS { get; set; }
        public string ESTADOPLANESTUDIOS { get; set; }
        public string CODIGOPLANESTUDIOS { get; set; }
    
        public virtual ICollection<ASIGNATURA> ASIGNATURAs { get; set; }
        public virtual PROGRAMA PROGRAMA { get; set; }
    }
}
