//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionUsuarios.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO
    {
        public PERMISO()
        {
            this.ROLs = new HashSet<ROL>();
        }
    
        public decimal IDENTIFICADORPERMISO { get; set; }
        public string NOMBREPERMISO { get; set; }
        public string ESTADOPERMISO { get; set; }
        public Nullable<decimal> GESTIONARPERMISO { get; set; }
    
        public virtual ICollection<ROL> ROLs { get; set; }
    }
}
