//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionInfraestructura.Datos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionInfraestructuraEntities : DbContext
    {
        public GestionInfraestructuraEntities()
            : base("name=GestionInfraestructuraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CURSO> CURSOes { get; set; }
        public DbSet<FACULTAD> FACULTADs { get; set; }
        public DbSet<FRANJA_HORARIA> FRANJA_HORARIA { get; set; }
        public DbSet<SALON> SALONs { get; set; }
    }
}
