//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionInfraestructura.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPORECURSO
    {
        public TIPORECURSO()
        {
            this.RECURSOes = new HashSet<RECURSO>();
        }
    
        public decimal IDTIPORECURSO { get; set; }
        public string NOMBRETIPORECURSO { get; set; }
        public Nullable<decimal> ESTADOTIPORECURSO { get; set; }
    
        public virtual ICollection<RECURSO> RECURSOes { get; set; }
    }
}
